[package]
name = "journ"
version = "0.2.1-beta.11"
description = "Plaintext Accounting Journal"
authors = ["Mark Barrett <mark@barrett.uk>"]
edition = "2024"
license = "AGPL-3"

[package.metadata]
contributors = ["Mark Barrett"]

[workspace]
members = ["core", "cag", "python"]

[dependencies]
journ-core = { path = "core" }
journ-cag = { path = "cag" }
chrono = { version = "0.4" }
chrono-tz = "0.10.3"
num-format = { version = "0.4", features = ["with-system-locale"] }
env_logger = "0.11.8"
bumpalo-herd = "0.1.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_trace"] }
sysinfo = { version = "0.32.0" }
clap = { version = "4.5.53", features = ["derive"] }


[profile.dev]
debug = true
opt-level = 0
lto = false

[profile.release]
debug = true
# This works to squeeze out better parsing performance, when integrating with nom.
# Disable while developing for faster builds.
lto = "fat"

[features]

[package.metadata.release]
pre-release-replacements = [
    # First capture group not working?
    { file = "dist/homebrew/journ.rb", search = '(url\s+"https://github.com/astralbat/journ/archive/refs/tags/)v[^"]+(\.tar\.gz")', replace = 'url      "https://github.com/astralbat/journ/archive/refs/tags/v{{version}}$2', prerelease = true, exactly = 1 }
]
