[package]
name = "journ-cag"
version = "0.2.1-beta.11"
authors = ["Mark Barrett <mark@barrett.uk>"]
edition = "2024"
license = "AGPL-3"
metadata = { contributors = ["Mark Barrett"] }

[dependencies]
journ-core = { path = "../core", version = "0.2.1-beta.11", features = ["testing"] }
chrono = { version = "0.4" }
chrono-tz = "0.10.3"
rust_decimal = "1.8.1"
rust_decimal_macros = "1.8.1"
itertools = "0.8.0"
smallvec = "1.4.2"
linked_hash_set = "0.1.4"
nom = "7.1.1"
yaml-rust2 = "0.11.0"
pyo3 = { version = "0.29.2", features = ["macros"] }
log = { version = "0.4.20", features = ["max_level_trace", "release_max_level_trace"] }
smartstring = "1.0.1"
clap = { version = "4.5.53", features = ["derive"] }

[dev-dependencies]
indoc = "1.0.7"

[features]
testing = []

