[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/python",
    "-C", "link-arg=-Wl,-rpath,/opt/homebrew/Frameworks",
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/python",
    "-C", "link-arg=-Wl,-rpath,/opt/homebrew/Frameworks",
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]